name: ros-kinetic-xenial

on:
  push

jobs:
  ros_kinetic_xenial_ci:
    name: kinetic (xenial)
    uses: ./.github/workflows/ros.yml
    with:
      ROS_DISTRO: kinetic
      ROS_REPO: testing
      OS_NAME: ubuntu
      OS_CODE_NAME: xenial
      ALLOW_FAIL: false